sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'travis-ci@design4.pro'
  - npm prune
script:
  - npm run build
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
